name: Deploy Terraform

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.9
      - name: Deploy Backend
        working-directory: ./backend
        run: ../.github/scripts/deploy.sh
        env:
          WORKSPACE: global
      - name: Deploy Bootstrap
        working-directory: ./bootstrap
        run: ../.github/scripts/deploy.sh
        env:
          WORKSPACE: global



